// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAetEub5vDb0AN9udMM-m7MZ8dcPNh87A',
    appId: '1:485401757910:web:9f43a4370237da8db0e177',
    messagingSenderId: '485401757910',
    projectId: 'learn-learn-d0f76',
    authDomain: 'learn-learn-d0f76.firebaseapp.com',
    databaseURL: 'https://learn-learn-d0f76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-learn-d0f76.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd_p-XLYKPk32UZZxFO0HY-alinysedPg',
    appId: '1:485401757910:android:7870da86e6a275e9b0e177',
    messagingSenderId: '485401757910',
    projectId: 'learn-learn-d0f76',
    databaseURL: 'https://learn-learn-d0f76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-learn-d0f76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCheE0z2zzraeQsmPHHtkBP7Hwbh8uaJb4',
    appId: '1:485401757910:ios:0fd36bc1d0d9e0cfb0e177',
    messagingSenderId: '485401757910',
    projectId: 'learn-learn-d0f76',
    databaseURL: 'https://learn-learn-d0f76-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'learn-learn-d0f76.firebasestorage.app',
    iosBundleId: 'com.example.rtcApp',
  );
}
